### ISSUE TITLE
Do wanna test! (and CI)

### ISSUE THREAD

**Issue by eggplants** [eggplants/wbsv-cli#12]
#11 
I'd like to use Coverage.

**Comment by eggplants** [comment]
Added apps of codacy and code climate for PR.

**Comment by victoriatomzik** [comment]
could you link Coverage, please? I've never heard of it.

**Comment by eggplants** [comment]
I'm sorry for my misunderstanding. "use Coverage" meant " measure Coverage".

**Comment by eggplants** [comment]
I'd like to test these commands:

```bash
wbsv -h
wbsv -V
wbsv
wbsv -L 0
wbsv -L 1 <url> (... <url n>)
wbsv -r 1 <url> (... <url n>)
wbsv -t <url> (... <url n>)
wbsv -d <url> (... <url n>)
```

**Comment by eggplants** [comment]
https://github.com/kvas-it/pytest-console-scripts
