### ISSUE TITLE
Colorize output and suppress it by opt

### ISSUE THREAD

**Issue by eggplants** [eggplants/wbsv-cli#3]
offにもできるようにする

**Comment by victoriatomzik** [comment]
Any ideas of how should it look like?

**Comment by eggplants** [comment]
e.g:
- `[+]` -> green
- `[!]` -> red
- Archived links -> white bold
- Index numbers (Like: `[xx/xx]`) -> white bold
- `<NOW>`/`<FAIL>` -> {green/yellow} background

(I haven't tried it out yet, so this color scheme might not be very cool.)

**Comment by eggplants** [comment]
And I will let this feature switch on and off by option like `-c, --color`

**Comment by eggplants** [comment]
面倒なのでやめる
