### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by victoriatomzik** [eggplants/wbsv-cli#55]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/17315148/89757493-b1963a80-dae5-11ea-80f3-4463a702b26c.png">

Seems like maybe savepagenow API changed a little? Not sure about it, just a guess since wbsv has been misbehaving for some time now.

**Comment by eggplants** [comment]
This error seem: https://github.com/pastpages/savepagenow/issues/26
Now I think to use: [waybackpy](https://github.com/akamhy/waybackpy)

**Comment by victoriatomzik** [comment]
Waybackpy looks really promising! :)
