### ISSUE TITLE
はじめてのコードレビュー

### ISSUE THREAD

**Issue by Ningensei848** [eggplants/wbsv-cli#9]
１．対象リポジトリからFork
２．issueを建てる（→issue numberが発行される）
３．branchを切る（→`feature/#issueNumber_Change_of_code`みたいな）
４．commitしてpush
５．PRを出す

cf. [gitのブランチの命名規則 - Qiita](https://qiita.com/luccafort/items/c91e817e78f1167221cc)
cf. [【GitHub】Pull Requestの手順 - Qiita](https://qiita.com/aipacommander/items/d61d21988a36a4d0e58b)

**Comment by eggplants** [comment]
#10 was merged! 
Thank you for your cooperation...😊
